### PR TITLE
more QOL changes to improve python style

### PR DESCRIPTION
**Pull request by CompRhys**
More QOL changes to the code summarised below:

1. fix the type error I introduced (oops!)
1. autoformat all the python scripts
1. add `.py` extension to the python scripts in `scripts` (including testing script)
1. update license for the current year
1. attempt to replace `optparse` with `argparse` where present given `optparse` is deprecated
1. use `np.pi` instead of `pyxtal.constants.pi`
1. fix the "L" in the ascii art logo
1. move imports to top in test file - runs 20% faster
1. add an indent to the Wyckoff sites in `__str__` representation of random crystal and random molecular crystal
1. refactor generate_crystal to break up the function into smaller parts

### CODE REVIEW

**Comment by CompRhys** [comment]
@qzhu2017 I have gone through the rest of the code and applied the same autoformatting with `black` and then fixed a few more things that caught my eye i.e. `optparse` I was starting to look at how to add the shake functionality and so began to refactor `generate_crystal` to try to make the code more modular add see whether it could be added in. Currently, I believe none of the functionality of the code has changed as the test script completes and so if these changes are acceptable to you it makes sense to merge them now and to have a separate PR for the shake functionality

**Comment by CompRhys** [comment]
It may also be worth considering changing the test suite to use `unittest` or `pytest` and then setting up a code action to check that the tests are passing in PRs to avoid the issue we have last time where I accidentally broke the tests

**Comment by qzhu2017** [comment]
@CompRhys Thanks, I will take a look and merge the pull request soon. Unittest is something which would be nice too. I just learned how to do it in my other projects. Will do it as well.

**Comment by qzhu2017** [comment]
@CompRhys 
I just merged you request and fixed a small bug 197684a

The codes look great now! Thanks

**Pull request merged**
